name: Build and Deploy GeoLift for WebR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.2.0'

    - name: Install remotes package
      run: Rscript -e "install.packages('remotes', repos='http://cran.us.r-project.org')"

    - name: Install Dependencies
      env:
        GITHUB_PAT: ${{ secrets.WEBR_PAT }}
      run: Rscript -e "remotes::install_github('ebenmichael/augsynth')"

    - name: Install GeoLift and WebR
      env:
        GITHUB_PAT: ${{ secrets.WEBR_PAT }}
      run: |
        Rscript -e "remotes::install_github('facebookincubator/GeoLift')"
        Rscript -e "remotes::install_github('r-wasm/webr')"

    - name: Set up Emscripten
      run: |
        git clone https://github.com/emscripten-core/emsdk.git
        cd emsdk
        ./emsdk install latest
        ./emsdk activate latest
        source ./emsdk_env.sh

    - name: Build WebR Package
      run: |
        source ./emsdk/emsdk_env.sh
        Rscript -e "webr::webr_build('GeoLift')"

    - name: Install r-wasm actions
      uses: r-wasm/actions/setup@v1

    - name: Build WebR binary
      run: Rscript -e "rwasm::rwasm_binary('GeoLift')"

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./GeoLift/build
        publish_branch: gh-pages
